### ISSUE TITLE
Votes on PRs before merging.

### ISSUE THREAD

**Issue by jcgruenhage** [afkollektiv/afkollektor.de#7]
Would be kinda cool if no one of us had write rights to the master branch, and only one bot had those rights, which would merge if the +1 votes would outweigh the -1 votes after either everyone (or 70% or something) had voted, or 48 hours had passed.

**Comment by Novare** [comment]
Disagree with the bot idea, only adds unneccessary maintainance. We should do the voting, though, and respect each other and the fact that we shouldn't merge obvious bullshit.

**Comment by jcgruenhage** [comment]
more bots -> longer toolchain -> profit?

**Comment by pbrinkmeier** [comment]
Yea i also think we dont need yet another bot, but we should lay out some ground rules for merging.

Proposal:

Only merge if
- 12h after the PR, yes votes are at least twice the no votes.
- 24h after the PR, yes votes are *more than* the no votes.
- Else, close the PR after 24h.

And maybe Jonas should have some kind of veto (after all, it's his domain).

**Comment by jcgruenhage** [comment]
that would mean we would need to wait at least 12 hours though

**Comment by pbrinkmeier** [comment]
Well, that's on purpose

**Comment by pbrinkmeier** [comment]
I think that the vote in the group was in favour of this, so we will keep it for the moment.

**Comment by jcgruenhage** [comment]
What I meant was this: imaging we have 8 positive votes after 2 hours, for some reason, we would still need to wait 10 hours, even though the majority has already voted in favour of it.

**Comment by jcgruenhage** [comment]
But whatever, overengineered af anyway
